.\" Report problems in https://github.com/hughsie/libjcat
.TH man 8 "11 April 2021" @PACKAGE_VERSION@ "jcat-tool man page"
.SH NAME
jcat-tool \- standalone detached signature utility
.SH SYNOPSIS
jcat-tool [CMD]
.SH DESCRIPTION
.PP
This manual page documents briefly the \fBjcat-tool\fR command.
.PP
\fBjcat-tool\fR allows a user to read, create and modify \fB.jcat\fR files.
.SH OPTIONS
The jcat-tool command takes various options depending on the action.
Run \fBjcat-tool --help\fR for the full list.
.SH SEE ALSO
certtool(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Richard Hughes (richard@hughsie.com)
